/**
 * @neutronai/gateway/upload — chunked resumable upload protocol.
 *
 * Three routes (all under `/api/upload/<source>/...` where `<source>`
 * is `chatgpt` or `claude`):
 *
 *   POST  /api/upload/<source>/start
 *     Mints an `upload_id`, creates a sparse temp file at
 *     `<owner_home>/imports/<upload_id>.part` sized to the full upload,
 *     persists a row in `upload_sessions`, returns
 *     `{ upload_id, chunk_size_bytes }`.
 *
 *   PATCH /api/upload/<source>/<upload_id>
 *     Accepts a chunk with `Content-Range: bytes <start>-<end>/<total>`.
 *     Writes the bytes at the requested offset (sparse-file rolls into a
 *     real allocation as chunks land). High-water-mark `bytes_received` is
 *     updated via SQL `MAX(...)` so a retried chunk doesn't regress the
 *     offset. On the final chunk the handler validates ZIP magic on the
 *     assembled file, moves it to `<owner_home>/imports/<source>.zip`,
 *     bridges into `engine.notifyImportUpload(...)` (same advance path as
 *     the legacy single-shot handler), DELETEs the session row, and
 *     returns `{ status: 'complete' }`. Partial-chunk PATCHes return
 *     `{ bytes_received }`.
 *
 *   HEAD  /api/upload/<source>/<upload_id>
 *     Returns 200 with `Upload-Offset: <bytes_received>` for any active
 *     session. 404 when the session is unknown OR expired (>24h since
 *     created_at OR status flipped to 'expired' by the sweeper).
 *
 * Borrows the SHAPE of tus.io but does NOT claim tus protocol
 * compatibility — no Tus-Resumable header, no creation extension, no
 * checksum extension. Lightweight by design.
 *
 * Why this exists: single-shot multipart POST on a 1.18 GB ChatGPT
 * export means a connection drop at 90% restarts from byte 0. Sam's
 * actual import on 2026-05-24 motivated the protocol replacement; this
 * handler is the server side. The client lives at
 * `landing/upload-client.ts` (web) and stays single-shot on the in-app
 * (RN) path for now (`app/lib/upload-client.ts` — out-of-scope per the
 * sprint brief).
 *
 * Sharing with the legacy single-shot handler:
 *   - MAX_UPLOAD_BYTES_DEFAULT (env-overridable size cap) is imported
 *     from `import-upload-handler.ts` so a single `NEUTRON_MAX_UPLOAD_BYTES`
 *     override applies to BOTH endpoints.
 *   - `engine.notifyImportUpload(...)` is called on completion with the
 *     same shape as the single-shot path so the InterviewEngine's
 *     `import_upload_pending` → `import_running` advance fires identically.
 *   - `X-Neutron-Topic-Id` resolution (per `import-upload-handler.ts`) is
 *     reused via the handler-input's `resolveTopicId` closure — production
 *     wires it to the same `extractTopicIdFromRequest` parser the legacy
 *     handler uses.
 */

import { randomUUID } from 'node:crypto'
import type { FileHandle } from 'node:fs/promises'
import { join } from 'node:path'

import type { ChannelKindForButton } from '../../channels/button-primitive.ts'
import { parseAnyTopicId } from '../../channels/topic-id.ts'
import type { InterviewEngine } from '../../onboarding/interview/engine.ts'
import { csrfForbiddenResponse, evaluateCsrfOrigin } from './csrf-origin-guard.ts'
import {
  extractTopicIdFromRequest,
  isUploadSource,
  MAX_UPLOAD_BYTES_DEFAULT,
  resolveEffectiveSource,
  SNIFF_MAX_BYTES,
  TOPIC_ID_FALLBACK,
  type UploadSource,
} from './import-upload-handler.ts'
import type { UploadSessionStore } from './upload-session-store.ts'

/**
 * Default chunk size returned to clients from `POST /start`. 4 MiB
 * balances per-PATCH HTTP overhead against memory pressure on the
 * per-instance gateway (one chunk's bytes are buffered before the disk
 * write). The client MAY use a different size, but the server-side
 * sparse file allows any aligned offsets so the value here is advisory.
 */
export const DEFAULT_CHUNK_SIZE_BYTES = 4 * 1024 * 1024

/**
 * Default upload-session TTL — 24 hours from `POST /start`. After this
 * the sweeper marks the row 'expired' and unlinks the partial file.
 * Clients that resume after the TTL passes get a 404 on `HEAD` and start
 * a fresh `/start`.
 */
export const DEFAULT_SESSION_TTL_MS = 24 * 60 * 60 * 1000

/**
 * `upload_id` is generated by `randomUUID()` (lowercase hex with dashes).
 * Validating the inbound id against this regex before any DB lookup or
 * disk path build prevents path traversal (`..`) and SQL-injection
 * payloads from ever reaching the persistence layer.
 */
const UPLOAD_ID_RE = /^[0-9a-f-]{32,40}$/i

/**
 * `Content-Range: bytes <start>-<end>/<total>`. RFC 7233 § 4.2 syntax,
 * restricted to absolute byte ranges (no `*` for unknown total). The
 * handler enforces `start <= end < total` and `end - start + 1 === body.byteLength`.
 */
const CONTENT_RANGE_RE = /^bytes\s+(\d+)-(\d+)\/(\d+)$/i

/** Header the chunked-upload handler reads off PATCH requests. */
export const CONTENT_RANGE_HEADER = 'content-range'

/** Header the chunked-upload handler reads off HEAD responses. */
export const UPLOAD_OFFSET_HEADER = 'Upload-Offset'

export interface ChunkedUploadInstanceContext {
  owner_home: string
  project_slug: string
  uid: number
  gid: number
  /** Routed through to `engine.notifyImportUpload` on completion. */
  topic_id: string
  channel_kind: ChannelKindForButton
  /** Optional onboarding user_id parsed off the topic_id (see
   *  `parseAnyTopicId`); threaded into the engine call so the state
   *  lookup hits the right `(project_slug, user_id)` row. */
  user_id?: string
}

export interface ChunkedUploadAuthResult {
  ok: boolean
  user_id?: string
}

/**
 * Filesystem seam. Only the verbs the handler actually uses — keeps the
 * test seam tight.
 */
export interface ChunkedUploadFs {
  mkdir(
    path: string,
    options: { recursive?: boolean; mode?: number },
  ): Promise<unknown>
  /** Open with the supplied mode bits ('w' for sparse-file create,
   *  'r+' for in-place chunk write, 'r' for the final magic-bytes read). */
  open(path: string, flags: string, mode?: number): Promise<FileHandle>
  chown(path: string, uid: number, gid: number): Promise<void>
  rename(src: string, dest: string): Promise<void>
  unlink(path: string): Promise<void>
}

export interface ChunkedUploadDeps {
  /** Optional auth gate. Same contract as the legacy single-shot handler. */
  auth?: (req: Request) => Promise<ChunkedUploadAuthResult>
  resolveInstanceContext: (req: Request) => Promise<ChunkedUploadInstanceContext | null>
  engine: Pick<InterviewEngine, 'notifyImportUpload'>
  store: UploadSessionStore
  /** Filesystem shim. Defaults to `node:fs/promises`. Test seam. */
  fs?: ChunkedUploadFs
  /** Override the size cap. Defaults to `MAX_UPLOAD_BYTES_DEFAULT`. */
  maxBytes?: number
  /** Override the advertised chunk size. Defaults to 4 MiB. */
  chunkSizeBytes?: number
  /** Override the session TTL. Defaults to 24 h. */
  sessionTtlMs?: number
  /** Clock seam. Defaults to `Date.now`. */
  now?: () => number
  /** UUID seam. Defaults to `crypto.randomUUID`. */
  uuid?: () => string
}

interface RouteMatch {
  source: UploadSource
  kind: 'start' | 'session'
  upload_id?: string
}

/**
 * Try to route `req` through the chunked-upload protocol. Returns a
 * `Response` when the request was owned (success or error), or `null`
 * when the path didn't match any of the three known shapes — the caller
 * (compose chain) falls through to the next handler.
 */
export async function handleChunkedUpload(
  req: Request,
  deps: ChunkedUploadDeps,
): Promise<Response | null> {
  const url = new URL(req.url)
  const match = matchChunkedRoute(url.pathname, req.method)
  if (match === null) return null

  // CSRF / Origin guard. Reject positively-detected cross-site requests on
  // every owned route (start / PATCH / HEAD) before any auth, body parse, or
  // disk write. Applied only after the route matched so non-owned paths still
  // fall through (return null) to the next handler in the compose chain.
  const csrf = evaluateCsrfOrigin(req)
  if (!csrf.allowed) {
    console.warn(
      `[chunked-upload] cross-site request rejected: ${csrf.reason} (${csrf.detail})`,
    )
    return csrfForbiddenResponse(csrf)
  }

  if (deps.auth !== undefined) {
    const authResult = await deps.auth(req)
    if (!authResult.ok) return jsonError(401, 'unauthorized')
  }
  const ctx = await deps.resolveInstanceContext(req)
  if (ctx === null) return jsonError(404, 'project not found')

  const fsImpl = deps.fs ?? (await resolveDefaultFs())
  if (match.kind === 'start') {
    return await handleStart(req, deps, fsImpl, ctx, match.source)
  }
  // PATCH or HEAD on /api/upload/<source>/<upload_id>.
  const upload_id = match.upload_id ?? ''
  if (!UPLOAD_ID_RE.test(upload_id)) {
    return jsonError(404, 'unknown upload session')
  }
  if (req.method === 'HEAD') {
    return await handleHead(deps, ctx, match.source, upload_id)
  }
  return await handlePatch(req, deps, fsImpl, ctx, match.source, upload_id)
}

function matchChunkedRoute(pathname: string, method: string): RouteMatch | null {
  // Normalise: every chunked path lives under `/api/upload/<source>/...`.
  // The shared prefix lets the legacy `POST /api/upload/<source>` route
  // sit alongside (compose.ts mounts chunked FIRST, so legacy only sees
  // the bare `/api/upload/<source>` shape — see compose.ts comment).
  const startMatch = pathname.match(/^\/api\/upload\/([^/]+)\/start$/)
  if (startMatch !== null && method === 'POST') {
    const source = startMatch[1] ?? ''
    if (!isUploadSource(source)) return null
    return { source, kind: 'start' }
  }
  const sessionMatch = pathname.match(/^\/api\/upload\/([^/]+)\/([^/]+)$/)
  if (sessionMatch !== null && (method === 'PATCH' || method === 'HEAD')) {
    const source = sessionMatch[1] ?? ''
    const upload_id = sessionMatch[2] ?? ''
    if (!isUploadSource(source)) return null
    // `start` is reserved — POST /start uses the start branch above; a
    // PATCH/HEAD on `.../start` falls out as a non-match here.
    if (upload_id === 'start') return null
    return { source, kind: 'session', upload_id }
  }
  return null
}

async function handleStart(
  req: Request,
  deps: ChunkedUploadDeps,
  fsImpl: ChunkedUploadFs,
  ctx: ChunkedUploadInstanceContext,
  source: UploadSource,
): Promise<Response> {
  let body: unknown
  try {
    body = await req.json()
  } catch (err) {
    return jsonError(
      400,
      `invalid JSON body: ${err instanceof Error ? err.message : 'unknown'}`,
    )
  }
  if (typeof body !== 'object' || body === null) {
    return jsonError(400, 'body must be a JSON object')
  }
  const fields = body as Record<string, unknown>
  const filename = fields['filename']
  const total_bytes = fields['total_bytes']
  const mime_type = fields['mime_type']
  if (typeof filename !== 'string' || filename.length === 0) {
    return jsonError(400, 'filename is required')
  }
  if (typeof mime_type !== 'string' || mime_type.length === 0) {
    return jsonError(400, 'mime_type is required')
  }
  if (typeof total_bytes !== 'number' || !Number.isFinite(total_bytes)) {
    return jsonError(400, 'total_bytes is required (number)')
  }
  if (!Number.isInteger(total_bytes) || total_bytes <= 0) {
    return jsonError(400, 'total_bytes must be a positive integer')
  }
  const maxBytes = deps.maxBytes ?? MAX_UPLOAD_BYTES_DEFAULT
  if (total_bytes > maxBytes) {
    return jsonError(
      413,
      `total_bytes ${total_bytes} exceeds cap ${maxBytes}`,
    )
  }
  // Strip path components from filename — clients send `export.zip` but
  // a misconfigured one could send `../foo` and we should never trust it
  // for any disk path. The temp file is keyed on upload_id, not filename;
  // we persist the filename only as a debugging breadcrumb.
  const safeFilename = filename.replace(/[/\\]/g, '_').slice(0, 255)

  const now = (deps.now ?? Date.now)()
  const uuid = (deps.uuid ?? randomUUID)()
  const importDir = join(ctx.owner_home, 'imports')
  const tempPath = tempFilePath(ctx.owner_home, uuid)
  try {
    await fsImpl.mkdir(importDir, { recursive: true, mode: 0o700 })
  } catch (err) {
    console.error(
      `[chunked-upload] project=${ctx.project_slug} mkdir failed: ${errMsg(err)}`,
    )
    return jsonError(500, 'could not create imports directory')
  }
  let handle: FileHandle
  try {
    handle = await fsImpl.open(tempPath, 'w', 0o600)
  } catch (err) {
    console.error(
      `[chunked-upload] project=${ctx.project_slug} open(${tempPath}) failed: ${errMsg(err)}`,
    )
    return jsonError(500, 'could not create temp file')
  }
  try {
    await handle.truncate(total_bytes)
  } catch (err) {
    console.error(
      `[chunked-upload] project=${ctx.project_slug} truncate(${total_bytes}) failed: ${errMsg(err)}`,
    )
    try {
      await handle.close()
    } catch {
      // swallow — best-effort close after a failed truncate
    }
    try {
      await fsImpl.unlink(tempPath)
    } catch {
      // swallow — temp file may not have landed
    }
    return jsonError(500, 'could not allocate temp file')
  }
  try {
    await handle.close()
  } catch (err) {
    console.warn(
      `[chunked-upload] project=${ctx.project_slug} close after truncate failed (non-fatal): ${errMsg(err)}`,
    )
  }
  // Best-effort chown — non-fatal on dev (single-user, CAP_CHOWN absent).
  try {
    await fsImpl.chown(tempPath, ctx.uid, ctx.gid)
  } catch (err) {
    console.warn(
      `[chunked-upload] project=${ctx.project_slug} chown(${tempPath}) failed (non-fatal): ${errMsg(err)}`,
    )
  }

  const ttl = deps.sessionTtlMs ?? DEFAULT_SESSION_TTL_MS
  try {
    await deps.store.create({
      upload_id: uuid,
      project_slug: ctx.project_slug,
      source,
      filename: safeFilename,
      total_bytes,
      mime_type,
      created_at: now,
      expires_at: now + ttl,
    })
  } catch (err) {
    console.error(
      `[chunked-upload] project=${ctx.project_slug} store.create failed: ${errMsg(err)}`,
    )
    try {
      await fsImpl.unlink(tempPath)
    } catch {
      // swallow — best-effort cleanup after DB write fail
    }
    return jsonError(500, 'could not persist upload session')
  }

  const chunk_size_bytes = deps.chunkSizeBytes ?? DEFAULT_CHUNK_SIZE_BYTES
  console.info(
    `[chunked-upload] project=${ctx.project_slug} source=${source} start upload_id=${uuid} total_bytes=${total_bytes} chunk_size=${chunk_size_bytes}`,
  )
  return Response.json({
    upload_id: uuid,
    chunk_size_bytes,
    total_bytes,
    expires_at: now + ttl,
  })
}

async function handleHead(
  deps: ChunkedUploadDeps,
  ctx: ChunkedUploadInstanceContext,
  source: UploadSource,
  upload_id: string,
): Promise<Response> {
  const row = await deps.store.get(upload_id)
  if (row === null) return new Response(null, { status: 404 })
  if (row.project_slug !== ctx.project_slug) return new Response(null, { status: 404 })
  if (row.source !== source) return new Response(null, { status: 404 })
  if (row.status !== 'uploading') return new Response(null, { status: 404 })
  const now = (deps.now ?? Date.now)()
  if (row.expires_at < now) return new Response(null, { status: 404 })
  return new Response(null, {
    status: 200,
    headers: {
      [UPLOAD_OFFSET_HEADER]: String(row.bytes_received),
      'Upload-Length': String(row.total_bytes),
      'Cache-Control': 'no-store',
    },
  })
}

async function handlePatch(
  req: Request,
  deps: ChunkedUploadDeps,
  fsImpl: ChunkedUploadFs,
  ctx: ChunkedUploadInstanceContext,
  source: UploadSource,
  upload_id: string,
): Promise<Response> {
  const row = await deps.store.get(upload_id)
  if (row === null) return jsonError(404, 'unknown upload session')
  if (row.project_slug !== ctx.project_slug) {
    // Different instance — same 404 as missing, intentionally indistinguishable.
    return jsonError(404, 'unknown upload session')
  }
  if (row.source !== source) {
    return jsonError(404, 'unknown upload session')
  }
  if (row.status === 'complete') {
    return jsonError(410, 'upload session already complete')
  }
  if (row.status === 'expired') {
    return jsonError(410, 'upload session expired')
  }
  const now = (deps.now ?? Date.now)()
  if (row.expires_at < now) {
    return jsonError(410, 'upload session expired')
  }

  const range = req.headers.get(CONTENT_RANGE_HEADER)
  if (range === null) {
    return jsonError(400, 'Content-Range header is required')
  }
  const parsed = parseContentRange(range)
  if (parsed === null) {
    return jsonError(400, `Content-Range malformed: ${range}`)
  }
  const { start, end, total } = parsed
  if (total !== row.total_bytes) {
    return jsonError(
      400,
      `Content-Range total ${total} does not match session total_bytes ${row.total_bytes}`,
    )
  }
  if (start < 0 || end < start || end >= row.total_bytes) {
    return jsonError(400, `Content-Range out of bounds: ${range}`)
  }
  // Gap detection — the chunked client is supposed to send chunks
  // contiguously and resume from `bytes_received` after a drop. A start
  // that's beyond bytes_received means the client lost track; reject so
  // the gap doesn't show up as a zeroed sparse hole in the final ZIP.
  if (start > row.bytes_received) {
    return new Response(
      JSON.stringify({
        ok: false,
        error: 'gap: start exceeds bytes_received',
        bytes_received: row.bytes_received,
      }),
      {
        status: 409,
        headers: {
          'Content-Type': 'application/json',
          [UPLOAD_OFFSET_HEADER]: String(row.bytes_received),
        },
      },
    )
  }
  const expected_chunk_len = end - start + 1
  const buf = await req.arrayBuffer()
  if (buf.byteLength !== expected_chunk_len) {
    return jsonError(
      400,
      `chunk length ${buf.byteLength} does not match Content-Range ${expected_chunk_len}`,
    )
  }

  const tempPath = tempFilePath(ctx.owner_home, upload_id)
  let handle: FileHandle
  try {
    handle = await fsImpl.open(tempPath, 'r+')
  } catch (err) {
    console.error(
      `[chunked-upload] project=${ctx.project_slug} open(${tempPath}) for chunk failed: ${errMsg(err)}`,
    )
    return jsonError(500, 'could not open temp file')
  }
  try {
    const bytes = new Uint8Array(buf)
    await handle.write(bytes, 0, bytes.byteLength, start)
  } catch (err) {
    console.error(
      `[chunked-upload] project=${ctx.project_slug} write(${tempPath}, start=${start}) failed: ${errMsg(err)}`,
    )
    try {
      await handle.close()
    } catch {
      // swallow
    }
    return jsonError(500, 'chunk write failed')
  }
  try {
    await handle.close()
  } catch (err) {
    console.warn(
      `[chunked-upload] project=${ctx.project_slug} close after chunk write failed (non-fatal): ${errMsg(err)}`,
    )
  }

  const candidate_offset = end + 1
  const new_bytes_received = await deps.store.updateBytesReceived(
    upload_id,
    candidate_offset,
  )
  if (new_bytes_received === null) {
    // Row vanished or status flipped between our read and the update —
    // race with the sweeper. Treat as expired.
    return jsonError(410, 'upload session expired')
  }

  if (new_bytes_received < row.total_bytes) {
    return Response.json({
      ok: true,
      bytes_received: new_bytes_received,
    })
  }

  // Final chunk landed (new_bytes_received >= total_bytes). Validate the
  // ZIP magic, move to the canonical destination, bridge into the engine,
  // delete the session row. Any failure path unwinds via the cleanup
  // branch — the partial file is unlinked and the row deleted so the
  // user can retry without orphaning state.
  return await finaliseUpload(
    deps,
    fsImpl,
    ctx,
    source,
    upload_id,
    row.filename,
    tempPath,
    row.total_bytes,
  )
}

async function finaliseUpload(
  deps: ChunkedUploadDeps,
  fsImpl: ChunkedUploadFs,
  ctx: ChunkedUploadInstanceContext,
  urlSource: UploadSource,
  upload_id: string,
  filename: string,
  tempPath: string,
  totalBytes: number,
): Promise<Response> {
  // 1. Magic-bytes check on the assembled file. Same `PK` prefix as the
  //    legacy single-shot handler.
  let magicOk = false
  try {
    const probe = await fsImpl.open(tempPath, 'r')
    try {
      const buf = new Uint8Array(4)
      const { bytesRead } = await probe.read(buf, 0, 4, 0)
      if (bytesRead >= 2 && buf[0] === 0x50 && buf[1] === 0x4b) {
        magicOk = true
      }
    } finally {
      try {
        await probe.close()
      } catch {
        // swallow
      }
    }
  } catch (err) {
    console.error(
      `[chunked-upload] project=${ctx.project_slug} magic-bytes read failed: ${errMsg(err)}`,
    )
    await cleanupFailedFinal(deps, fsImpl, tempPath, upload_id)
    return jsonError(500, 'could not read assembled file')
  }
  if (!magicOk) {
    await cleanupFailedFinal(deps, fsImpl, tempPath, upload_id)
    return jsonError(400, 'not a zip file (magic bytes mismatch)')
  }

  // 1.5. Sniff the REAL source from the assembled zip's entry list. The web
  //      affordance hardcodes `/api/upload/chatgpt`, so a Claude export needs
  //      to be re-routed to the Claude parser. The minimal zip reader needs the
  //      whole archive in memory; skip the sniff above SNIFF_MAX_BYTES (and on
  //      any read error) and keep the URL source — the sniff must NEVER break
  //      an otherwise-complete upload.
  const source = await sniffAssembledSource(fsImpl, tempPath, totalBytes, urlSource)

  // 2. Rename to the canonical destination. Same path the legacy
  //    single-shot handler writes to so the import-runner finds it.
  const destPath = join(ctx.owner_home, 'imports', `${source}.zip`)
  try {
    await fsImpl.rename(tempPath, destPath)
  } catch (err) {
    console.error(
      `[chunked-upload] project=${ctx.project_slug} rename(${tempPath} -> ${destPath}) failed: ${errMsg(err)}`,
    )
    await cleanupFailedFinal(deps, fsImpl, tempPath, upload_id)
    return jsonError(500, 'could not move assembled file into place')
  }
  // 3. Best-effort chown on the final file — non-fatal.
  try {
    await fsImpl.chown(destPath, ctx.uid, ctx.gid)
  } catch (err) {
    console.warn(
      `[chunked-upload] project=${ctx.project_slug} chown(${destPath}) failed (non-fatal): ${errMsg(err)}`,
    )
  }
  console.info(
    `[chunked-upload] project=${ctx.project_slug} source=${source} complete upload_id=${upload_id} filename=${filename} destination=${destPath}`,
  )

  // 4. Bridge into the InterviewEngine — same shape as the legacy
  //    single-shot handler's notify call so the `import_upload_pending`
  //    → `import_running` advance fires identically.
  let advanceJobId: string | null = null
  let advanceOutcome = 'unknown'
  try {
    const advance = await deps.engine.notifyImportUpload({
      project_slug: ctx.project_slug,
      topic_id: ctx.topic_id,
      user_id: ctx.user_id ?? '',
      channel_kind: ctx.channel_kind,
      source,
    })
    advanceOutcome = advance.outcome
    const phaseState = (advance.state?.phase_state as Record<string, unknown> | undefined) ?? {}
    const jobId = phaseState['import_job_id']
    if (typeof jobId === 'string') advanceJobId = jobId
  } catch (err) {
    // Engine errors surface as 500 — the bytes are on disk so the import
    // is salvageable manually, but the user-visible flow needs the
    // engine advance to fire. Same severity as the legacy handler's
    // engine-notify-failed branch.
    console.error(
      `[chunked-upload] project=${ctx.project_slug} engine notify failed: ${errMsg(err)}`,
    )
    // Keep the bytes on disk + delete the session row. The user retrying
    // the upload would land a fresh ZIP at the same path, which the
    // engine runner handles.
    try {
      await deps.store.deleteSession(upload_id)
    } catch {
      // swallow — best-effort
    }
    return jsonError(500, `engine notify failed: ${errMsg(err)}`)
  }

  // 5. DELETE the session row. Idempotent — re-runs are no-ops.
  try {
    await deps.store.deleteSession(upload_id)
  } catch (err) {
    console.warn(
      `[chunked-upload] project=${ctx.project_slug} store.deleteSession failed (non-fatal): ${errMsg(err)}`,
    )
  }

  return Response.json({
    ok: true,
    status: 'complete',
    source,
    destination: destPath,
    outcome: advanceOutcome,
    job_id: advanceJobId,
  })
}

async function cleanupFailedFinal(
  deps: ChunkedUploadDeps,
  fsImpl: ChunkedUploadFs,
  tempPath: string,
  upload_id: string,
): Promise<void> {
  try {
    await fsImpl.unlink(tempPath)
  } catch {
    // swallow — temp file may have already been moved
  }
  try {
    await deps.store.deleteSession(upload_id)
  } catch {
    // swallow — DB may already be cleaned
  }
}

/**
 * Read the assembled temp file and sniff its real export source (see
 * `resolveEffectiveSource` / `sniffZipSource` in `import-upload-handler.ts`).
 * Bounded + fully defensive: above {@link SNIFF_MAX_BYTES} (a heavy ChatGPT
 * export) OR on any read failure we skip the sniff and keep the URL source —
 * the sniff must NEVER block an otherwise-complete upload. `totalBytes` is the
 * session's declared (and fully-written) size, so it is the exact file length.
 */
async function sniffAssembledSource(
  fsImpl: ChunkedUploadFs,
  tempPath: string,
  totalBytes: number,
  urlSource: UploadSource,
): Promise<UploadSource> {
  if (totalBytes <= 0 || totalBytes > SNIFF_MAX_BYTES) return urlSource
  let buf: Buffer
  try {
    const handle = await fsImpl.open(tempPath, 'r')
    try {
      buf = Buffer.alloc(totalBytes)
      await handle.read(buf, 0, totalBytes, 0)
    } finally {
      try {
        await handle.close()
      } catch {
        // swallow — best-effort close
      }
    }
  } catch (err) {
    console.warn(
      `[chunked-upload] source sniff read failed (non-fatal, keeping url source ${urlSource}): ${errMsg(err)}`,
    )
    return urlSource
  }
  return resolveEffectiveSource(urlSource, buf, (msg) => console.info(msg))
}

function tempFilePath(owner_home: string, upload_id: string): string {
  return join(owner_home, 'imports', `${upload_id}.part`)
}

export interface ParsedContentRange {
  start: number
  end: number
  total: number
}

export function parseContentRange(value: string): ParsedContentRange | null {
  const match = value.trim().match(CONTENT_RANGE_RE)
  if (match === null) return null
  const start = Number(match[1])
  const end = Number(match[2])
  const total = Number(match[3])
  if (!Number.isInteger(start) || !Number.isInteger(end) || !Number.isInteger(total)) {
    return null
  }
  if (start < 0 || end < 0 || total <= 0) return null
  return { start, end, total }
}

function jsonError(status: number, message: string): Response {
  return Response.json({ ok: false, error: message }, { status })
}

function errMsg(err: unknown): string {
  return err instanceof Error ? err.message : String(err)
}

let _defaultFsPromise: Promise<ChunkedUploadFs> | null = null
async function resolveDefaultFs(): Promise<ChunkedUploadFs> {
  if (_defaultFsPromise === null) {
    _defaultFsPromise = (async (): Promise<ChunkedUploadFs> => {
      const mod = await import('node:fs/promises')
      // Bind methods so callers can destructure or reuse closures
      // without losing the module's `this`.
      return {
        mkdir: (path, opts) => mod.mkdir(path, opts),
        open: (path, flags, mode) => mod.open(path, flags, mode),
        chown: (path, uid, gid) => mod.chown(path, uid, gid),
        rename: (src, dest) => mod.rename(src, dest),
        unlink: (path) => mod.unlink(path),
      }
    })()
  }
  return _defaultFsPromise
}

/**
 * Inputs to {@link buildChunkedUploadHandler}. Mirrors the
 * `BuildImportUploadHandlerInput` shape so the per-instance boot wires
 * both handlers off the same primitives (owner_home, uid/gid,
 * project_slug, engine).
 */
export interface BuildChunkedUploadHandlerInput {
  owner_home: string
  uid: number
  gid: number
  project_slug: string
  engine: Pick<InterviewEngine, 'notifyImportUpload'>
  store: UploadSessionStore
  /** Filesystem shim — defaulted to `node:fs/promises` inside the closure. */
  fs?: ChunkedUploadFs
  /** Override the size cap (tests). */
  maxBytes?: number
  /** Override the advertised chunk size (tests). */
  chunkSizeBytes?: number
  /** Override the session TTL (tests). */
  sessionTtlMs?: number
  /** Optional sink for the once-per-process deprecation log fired when the
   *  inbound `X-Neutron-Topic-Id` header is missing on a chunked-upload
   *  request. Mirrors the legacy handler's flag. */
  onTopicIdMissing?: () => void
}

/**
 * Build the production chunked-upload handler closure. Mirrors
 * `buildImportUploadHandler` from `import-upload-handler.ts` so the
 * per-instance boot wires both off identical primitives.
 *
 * Returns `null` for paths that don't match any of the three chunked
 * routes — the compose chain falls through to the legacy single-shot
 * handler (which owns the bare `POST /api/upload/<source>` shape).
 */
export function buildChunkedUploadHandler(
  input: BuildChunkedUploadHandlerInput,
): (req: Request) => Promise<Response | null> {
  let warned = false
  return async (req: Request): Promise<Response | null> => {
    const deps: ChunkedUploadDeps = {
      resolveInstanceContext: async (innerReq) => {
        const header = extractTopicIdFromRequest(innerReq)
        const topic_id = header ?? TOPIC_ID_FALLBACK
        if (header === null && !warned) {
          warned = true
          if (input.onTopicIdMissing !== undefined) {
            try {
              input.onTopicIdMissing()
            } catch {
              // swallow — the once-per-process notice is best-effort
            }
          }
        }
        const parsed = parseAnyTopicId(topic_id)
        const ctx: ChunkedUploadInstanceContext = {
          owner_home: input.owner_home,
          project_slug: input.project_slug,
          uid: input.uid,
          gid: input.gid,
          topic_id,
          channel_kind: 'app-socket',
        }
        if (parsed?.user_id !== undefined) ctx.user_id = parsed.user_id
        return ctx
      },
      engine: input.engine,
      store: input.store,
    }
    if (input.fs !== undefined) deps.fs = input.fs
    if (input.maxBytes !== undefined) deps.maxBytes = input.maxBytes
    if (input.chunkSizeBytes !== undefined) deps.chunkSizeBytes = input.chunkSizeBytes
    if (input.sessionTtlMs !== undefined) deps.sessionTtlMs = input.sessionTtlMs
    return handleChunkedUpload(req, deps)
  }
}
