/**
 * Codex P1 fix on PR #124 (S13) regression suite — per-instance `.env`
 * overlay loader. The lazy `resolvePool` closure in `gateway/index.ts`
 * MUST re-read this overlay on every import dispatch so a credential
 * written to `.env` after the gateway is up (synthetic-auth race,
 * Max OAuth attach mid-session) becomes visible without `systemctl
 * restart` re-execing the unit.
 */

import { afterEach, beforeEach, expect, test } from 'bun:test'
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import {
  loadInstanceEnvOverlay,
  parseEnvFileBody,
} from '../load-instance-env-overlay.ts'

let owner_home: string

beforeEach(() => {
  owner_home = mkdtempSync(join(tmpdir(), 'neutron-env-overlay-'))
})

afterEach(() => {
  rmSync(owner_home, { recursive: true, force: true })
})

test('loadInstanceEnvOverlay returns {} when .env is absent', () => {
  expect(loadInstanceEnvOverlay(owner_home)).toEqual({})
})

test('loadInstanceEnvOverlay returns {} on empty / non-string owner_home', () => {
  expect(loadInstanceEnvOverlay('')).toEqual({})
  // Type-narrow lies are how production sometimes calls us — defensive.
  expect(loadInstanceEnvOverlay(undefined as unknown as string)).toEqual({})
})

test('parses the synthetic-test-owner.sh shape (comments + KEY=VALUE lines)', () => {
  writeFileSync(
    join(owner_home, '.env'),
    [
      '# Generated by synthetic-test-owner.sh',
      '# slug=casey-test',
      'CLAUDE_CODE_OAUTH_TOKEN=mx-oauth-deadbeef',
      'ANTHROPIC_API_KEY=sk-ant-test',
      'ANTHROPIC_API_KEY_CASEY_TEST=sk-ant-test',
      '',
    ].join('\n'),
  )
  const overlay = loadInstanceEnvOverlay(owner_home)
  expect(overlay).toEqual({
    CLAUDE_CODE_OAUTH_TOKEN: 'mx-oauth-deadbeef',
    ANTHROPIC_API_KEY: 'sk-ant-test',
    ANTHROPIC_API_KEY_CASEY_TEST: 'sk-ant-test',
  })
})

test('strips matching single + double quotes around values', () => {
  const body = [
    'KEY1="quoted"',
    "KEY2='single'",
    'KEY3=unquoted',
    'KEY4="mismatched\'',
  ].join('\n')
  expect(parseEnvFileBody(body)).toEqual({
    KEY1: 'quoted',
    KEY2: 'single',
    KEY3: 'unquoted',
    KEY4: `"mismatched'`,
  })
})

test('honours optional `export ` prefix (systemd accepts, ignores it)', () => {
  expect(parseEnvFileBody('export FOO=bar\nBAZ=qux')).toEqual({
    FOO: 'bar',
    BAZ: 'qux',
  })
})

test('skips invalid key shapes (starts with digit, contains hyphen, empty)', () => {
  const body = [
    '1FOO=bad',
    'BAR-BAZ=bad',
    '=novalue',
    'OK=good',
    'OK_UNDERSCORE=good',
    '_LEADING_OK=good',
  ].join('\n')
  expect(parseEnvFileBody(body)).toEqual({
    OK: 'good',
    OK_UNDERSCORE: 'good',
    _LEADING_OK: 'good',
  })
})

test('handles CRLF and bare CR line endings the same as LF', () => {
  const body = 'FOO=1\r\nBAR=2\rBAZ=3\n'
  expect(parseEnvFileBody(body)).toEqual({ FOO: '1', BAR: '2', BAZ: '3' })
})

test('a corrupted (binary) .env does NOT crash the loader', () => {
  // Random binary garbage interleaved with a KEY=VALUE line. The
  // utf8-decoded body MAY mangle the GOOD line into an invalid-key
  // shape (replacement chars at byte boundaries), which is fine — the
  // contract this test pins is "must not throw". An empty overlay AND
  // an overlay containing GOOD are both acceptable.
  writeFileSync(
    join(owner_home, '.env'),
    Buffer.concat([
      Buffer.from('\x00\x01\x02\n', 'binary'),
      Buffer.from('GOOD=present\n', 'utf8'),
      Buffer.from('\xff\xfe\n', 'binary'),
    ]),
  )
  expect(() => loadInstanceEnvOverlay(owner_home)).not.toThrow()
})

test('returns {} when .env exceeds the 64KB size cap (defensive bound)', () => {
  // 64KB + 1 of legitimately-shaped lines.
  const line = 'KEY_ABCDEFGHIJKLMN=' + 'x'.repeat(80) + '\n'
  const repeats = Math.ceil((64 * 1024 + 1) / line.length)
  writeFileSync(join(owner_home, '.env'), line.repeat(repeats))
  expect(loadInstanceEnvOverlay(owner_home)).toEqual({})
})
