/**
 * @neutronai/onboarding/telemetry — public barrel (P2 S6).
 *
 * Per docs/plans/P2-onboarding.md § 5 + § 9.5.
 */

export {
  ALL_ONBOARDING_EVENT_NAMES,
  LEGACY_ATTEMPT_ID,
  OnboardingTelemetry,
  buildProductionOnboardingTelemetry,
  buildStdoutEventLogger,
  moduleForEventName,
  type EventLogger,
  type OnboardingEvent,
  type OnboardingEventLevel,
  type OnboardingEventModule,
  type OnboardingEventName,
  type OnboardingEventPayloadByName,
  type OnboardingTelemetryDeps,
  type PersistedOnboardingEvent,
  // Per-event payload schemas
  type ArchetypeLlmExtensionPayload,
  type ArchetypePickedPayload,
  type ButtonChosenPayload,
  type ButtonEmittedPayload,
  type ButtonFreeformPayload,
  type ButtonTimeoutPayload,
  type ImportPass1ChunkDonePayload,
  type ImportPass2CompletePayload,
  type ImportStartedPayload,
  type OnboardingAbandonedPayload,
  type OnboardingCompletedPayload,
  type OnboardingFailedPayload,
  type Pass2SonnetFallbackUsedPayload,
  type PersonaCommittedPayload,
  type PersonaCringeFlaggedPayload,
  type PersonaDraftedPayload,
  type PersonaRegenPayload,
  type PhaseAdvancedPayload,
  type ProfilePicFallbackPayload,
  type ProfilePicGeneratedPayload,
  type ProfilePicUserUploadedPayload,
  type SeanEllisPromptEmittedPayload,
  type SeanEllisResponsePayload,
  type SignupOauthCompletePayload,
  type SignupStartedPayload,
  type SignupInstanceProvisionedPayload,
  type WowActionEngagedPayload,
  type WowActionFiredPayload,
  type WowActionSkippedPayload,
  type WowDispatchedPayload,
} from './event-emitter.ts'

export {
  DEFAULT_CHECK_INTERVAL_MS,
  FOUR_WEEKS_MS,
  SEAN_ELLIS_HANDLER_NAME,
  SEAN_ELLIS_PROMPT_BODY,
  SEAN_ELLIS_PROMPT_OPTIONS,
  SeanEllisStore,
  buildSeanEllisHandler,
  buildSeanEllisJob,
  registerSeanEllisCron,
  type SeanEllisChannel,
  type SeanEllisHandlerDeps,
  type SeanEllisRow,
} from './sean-ellis-trigger.ts'

export {
  bridgeArchetypeTelemetry,
  bridgeCompletionTelemetry,
  bridgeImportTelemetry,
  bridgeInterviewTelemetry,
  bridgePersonaTelemetry,
  bridgeProfilePicTelemetry,
  bridgeSignupTelemetry,
  bridgeWowEventLogger,
  composeOnboardingTelemetrySinks,
  type ArchetypeTelemetrySink,
  type BridgeWowDefaults,
  type CompletionTelemetrySink,
  type ComposedTelemetrySinks,
  type ImportTelemetrySink,
  type InterviewTelemetrySink,
  type PersonaTelemetrySink,
  type ProfilePicTelemetrySink,
  type SignupTelemetrySink,
} from './composition.ts'
